CREATE DATABASE DB_SERVICO_RH;

USE DB_SERVICO_RH;

CREATE TABLE TB_FUNCIONARIO(
REGISTRO BIGINT AUTO_INCREMENT,
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
SALARIO INT,
JORNADA INT,
PRIMARY KEY (REGISTRO)
);
INSERT INTO TB_FUNCIONARIO (NOME,IDADE,FUNCAO,SALARIO,JORNADA)
VALUES ("JULIANA",25,"DEVA",5.000,"8 HORAS DIARIAS");
INSERT INTO TB_FUNCIONARIO (NOME,IDADE,FUNCAO,SALARIO,JORNADA)
VALUES ("MARIA",21,"DEVA",1.500,"6 HORAS DIARIAS");
INSERT INTO TB_FUNCIONARIO (NOME,IDADE,FUNCAO,SALARIO,JORNADA)
VALUES ("JOANA",28,"DEVA",1.000,"4 HORAS DIARIAS");
INSERT INTO TB_FUNCIONARIO (NOME,IDADE,FUNCAO,SALARIO,JORNADA)
VALUES ("MARCELA",18,"DEVA",5.000,"8 HORAS DIARIAS");

SELECT*FROM TB_FUNCIONARIO;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO >2.000;
SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO <2.000;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_EMPREGADO SET SALARIO = 2.000 WHERE REGISTRO = 4;
