CREATE DATABASE DB_ECOMMERCE;
USE DB_ECOMMERCE;

CREATE TABLE TB_PRODUTOS (
ID BIGINT AUTO_INCREMENT,
NOME CHAR (255),
PRECO DECIMAL,
TAMANHOS CHAR (255),
DESCRICAO VARCHAR (1000),
PRIMARY KEY (ID)
);

INSERT INTO TB_PRODUTOS (NOME, PRECO, TAMANHOS, DESCRICAO)
VALUES ("CAMISETA", 130, "P, M, G E GG", "CAMISETA BABYLOOK ALGODÃO");
INSERT INTO TB_PRODUTOS (NOME, PRECO, TAMANHOS,DESCRICAO)
VALUES ("CALÇA SARUEL", 550, "P, M, G", "CALÇA JEANS SARUEL");
INSERT INTO TB_PRODUTOS (NOME, PRECO, TAMANHOS,DESCRICAO)
VALUES ("SHORTS", 890, "P,M, G E GG", "SHORTS JEANS MOM");
INSERT INTO TB_PRODUTOS (NOME, PRECO, TAMANHOS, DESCRICAO)
VALUES ("PIJAMA", 55, "P,M,G E GG","PIJAMA LUXO SEDA");

SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_PRODUTOS WHERE PRECO > 500;
SELECT * FROM TB_PRODUTOS WHERE PRECO < 500;

UPDATE TB_PRODUTOS SET TAMANHOS = "P,M,G" WHERE ID = 4