CREATE DATABASE DB_JUSCHOOL;

USE DB_JUSCHOOL;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
ANO INT,
TURMA CHAR(255),
MEDIA FLOAT,
PERIODO CHAR(255),
PRIMARY KEY (ID)
);

INSERT INTO TB_ALUNOS (NOME, ANO, TURMA, MEDIA, PERIODO)
VALUES("ANA", 8, "B", 9.0, "MANHA");
INSERT INTO TB_ALUNOS (NOME, ANO, TURMA, MEDIA, PERIODO)
VALUES("AGATHA", 2, "A", 6.0,"TARDE");
INSERT INTO TB_ALUNOS (NOME, ANO, TURMA, MEDIA, PERIODO)
VALUES("LUIZ", 4, "D", 10.0,"NOITE");

SELECT * FROM TB_ALUNOS;
SELECT * FROM TB_ALUNOS WHERE MEDIA > 7;
SELECT * FROM TB_ALUNOS WHERE MEDIA < 7;

ALTER TABLE TB_ALUNOS MODIFY MEDIA FLOAT(5.0);
UPDATE TB_ALUNOS SET MEDIA = 8.0 WHERE ID = 1;
UPDATE TB_ALUNOS SET MEDIA = 5.0 WHERE ID = 2;