CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID bigint(5) auto_increment,
TIPO VARCHAR(255) NOT NULL,
HABILIDADE VARCHAR(255) NOT NULL,
PRIMARY KEY(ID));

CREATE TABLE TB_PERSONAGENS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
ATAQUE INT NOT NULL,
DEFESA INT NOT NULL,
EQUIPAMENTO INT NOT NULL,
CATEGORIA_ID BIGINT(5),
PRIMARY KEY(ID),
FOREIGN KEY(CLASSES_ID) REFERENCES TB_CLASSES(ID)
);

SELECT * FROM TB_PRODUTOS;

INSERT INTO TB_CLASSES(TIPO,HABILIDADE)
VALUES("MAGO","VOA");
INSERT INTO TB_CLASSES(TIPO,HABILIDADE)
VALUES("REI","FORÇA");
INSERT INTO TB_CLASSES(TIPO,HABILIDADE)
VALUES("GUERREIRO","VISÃO");

